image: node:8.9

cache:
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  only:
    - master
  script:
    - npm run build
    - mv docs public
  artifacts:
    paths:
      - public
